kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  argocd:
    # https://artifacthub.io/packages/helm/bitnami/argo-cd
    chartVersion: 6.0.10
  certmanager:
    # https://github.com/cert-manager/cert-manager/releases
    chartVersion: v1.14.3
  cloudnativepg:
    # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    chartVersion: 0.20.1
  console:
    # https://github.com/cloud-pi-native/console/releases
    release: "8.0.2"
  gitlab:
    # https://artifacthub.io/packages/helm/gitlab/gitlab
    chartVersion: "7.9.2"
  gitlabOperator:
    # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/tags
    chartVersion: "0.29.2"
  gitlabRunner:
    # https://gitlab.com/gitlab-org/charts/gitlab-runner/-/tags
    chartVersion: "0.62.0"
  grafana:
    # https://github.com/grafana/grafana/tags
    imageVersion: "9.5.5"
  grafanaOperator:
    # https://github.com/grafana/grafana-operator/tags
    chartVersion: "v5.4.2"
  harbor:
    # https://artifacthub.io/packages/helm/harbor/harbor
    chartVersion: 1.14.1
  keycloak:
    # https://artifacthub.io/packages/helm/bitnami/keycloak
    chartVersion: 19.3.4
  kyverno:
    # https://artifacthub.io/packages/helm/kyverno/kyverno
    chartVersion: 3.1.4
  nexus:
    # https://hub.docker.com/r/sonatype/nexus3/
    imageTag: 3.66.0
  sonarqube:
    # https://artifacthub.io/packages/helm/sonarqube/sonarqube
    chartVersion: 10.4.1+2389
  vault:
    # https://artifacthub.io/packages/helm/hashicorp/vault
    chartVersion: 0.25.0
