kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  argocd:
    # https://artifacthub.io/packages/helm/argo/argo-cd
    chartVersion: 7.7.8
  certmanager:
    # https://github.com/cert-manager/cert-manager/releases
    chartVersion: v1.14.3
  cloudnativepg:
    # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    chartVersion: 0.20.1
  console:
    # https://github.com/cloud-pi-native/console/releases
    release: "2.*.*"
  gitlab:
    # https://artifacthub.io/packages/helm/gitlab/gitlab
    chartVersion: "8.8.1"
  gitlabCiPipelinesExporter:
    # https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
    chartVersion: "0.3.4"
  gitlabOperator:
    # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/tags
    chartVersion: "1.9.1"
  gitlabRunner:
    # https://gitlab.com/gitlab-org/charts/gitlab-runner/-/tags
    chartVersion: "0.73.3"
  grafana:
    # https://github.com/grafana/grafana/tags
    imageVersion: "10.4.3"
  grafanaOperator:
    # https://github.com/grafana/grafana-operator/tags
    chartVersion: "v5.10.0"
  harbor:
    # https://artifacthub.io/packages/helm/harbor/harbor
    chartVersion: 1.16.0
  keycloak:
    # https://artifacthub.io/packages/helm/bitnami/keycloak
    chartVersion: 24.2.3
  kyverno:
    # https://artifacthub.io/packages/helm/kyverno/kyverno
    chartVersion: 3.1.4
  nexus:
    # https://hub.docker.com/r/sonatype/nexus3/
    imageTag: 3.76.0
  sonarqube:
    # https://artifacthub.io/packages/helm/sonarqube/sonarqube
    chartVersion: 10.8.1
  vault:
    # https://artifacthub.io/packages/helm/hashicorp/vault
    chartVersion: 0.29.1
