kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  argocd:
    # https://artifacthub.io/packages/helm/bitnami/argo-cd
    chartVersion: 4.7.19
  certmanager:
    # https://github.com/cert-manager/cert-manager/releases
    chartVersion: v1.13.1
  cloudnativepg:
    # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    chartVersion: 0.18.2
  console:
    # https://github.com/cloud-pi-native/console/releases
    release: "6.5.1"
  gitlab:
    # https://artifacthub.io/packages/helm/gitlab/gitlab
    chartVersion: "7.6.6"
  gitlabOperator:
    # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/tags
    chartVersion: "0.28.1"
  gitlabRunner:
    # https://gitlab.com/gitlab-org/charts/gitlab-runner/-/tags
    chartVersion: "0.59.1"
  grafana:
    # https://github.com/grafana/grafana/tags
    imageVersion: "9.5.5"
  grafanaOperator:
    # https://github.com/grafana/grafana-operator/tags
    chartVersion: "v5.4.2"
  harbor:
    # https://artifacthub.io/packages/helm/harbor/harbor
    chartVersion: 1.13.1
  keycloak:
    # https://artifacthub.io/packages/helm/bitnami/keycloak
    chartVersion: 16.1.5
  kubed:
    # https://artifacthub.io/packages/helm/appscode/kubed
    chartVersion: 0.13.2
  nexus:
    # https://hub.docker.com/r/sonatype/nexus3/
    imageTag: 3.56.0
  sonarqube:
    # https://artifacthub.io/packages/helm/sonarqube/sonarqube
    chartVersion: 10.2.1+800
  vault:
    # https://artifacthub.io/packages/helm/hashicorp/vault
    chartVersion: 0.25.0
