apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-secret
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: "zone-{{ .Values.zoneName }}"
  path: keycloak
  destination:
    create: true
    name: oidc-secret
    labels:
      'app.kubernetes.io/part-of': 'argocd'