---
- name: Missing Token disclaimer
  ansible.builtin.debug:
    msg: Impossible de retrouver le TOKEN du compte admin, initialisation en cours â€¦

- name: Remove old admin token
  ansible.builtin.uri:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    url: "{{ sonar_auth_url }}/api/user_tokens/revoke?name=DSO"
    user: "admin"
    password: "{{ sonarqube_pwd.resources[0].data.password | b64decode }}"
    force_basic_auth: true
    method: post
    status_code: [200, 204, 404]
  register: current_tokens

- name: Generate new SonarQube DSO admin token
  ansible.builtin.uri:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    url: "{{ sonar_auth_url }}/api/user_tokens/generate?name=DSO"
    user: "admin"
    password: "{{ sonarqube_pwd.resources[0].data.password | b64decode }}"
    force_basic_auth: true
    method: POST
    status_code: [200, 204]
  register: token_pass

- name: Set retrieved_token_pass fact
  ansible.builtin.set_fact:
    retrieved_token_pass: "{{ token_pass.json.token }}"
