apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cas
  namespace: openshift-config
data:
  "{{ harbor_domain }}": |
{% filter indent(width=4) %}
    {{ harbor_crt.resources[0].data['tls.crt'] | b64decode }}
{% endfilter %}